/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for Assignement AST Node type
  * by the ASTNode.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

import static de.compilerbau.NewAwkCompiler.javacc21.NewAwkConstants.TokenType.*;
@SuppressWarnings("unused")
public class Assignement extends BaseNode {

    public ID id = null;
    public ExprStmnt exprStmnt = null;

    public Object jjtAccept(NewAwkParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
