/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for CARRIAGE_RETURN Token subclass
  * by the ASTToken.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

@SuppressWarnings("unused")
public class CARRIAGE_RETURN extends Token {
    public CARRIAGE_RETURN(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

    public CARRIAGE_RETURN(TokenType type, String image, FileLineMap fileLineMap) {
        super(type, image, fileLineMap);
    }

}
