/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for CHAR_CLASS Token subclass
  * by the ASTToken.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

import static de.compilerbau.NewAwkCompiler.javacc21.NewAwkConstants.TokenType.*;
@SuppressWarnings("unused")
public class CHAR_CLASS extends Token {
    public CHAR_CLASS(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

    public CHAR_CLASS(TokenType type, String image, FileLineMap fileLineMap) {
        super(type, image, fileLineMap);
    }

}
