/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for ExprStmnt AST Node type
  * by the ASTNode.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

import static de.compilerbau.NewAwkCompiler.javacc21.NewAwkConstants.TokenType.*;
@SuppressWarnings("unused")
public class ExprStmnt extends BaseNode {

    /* TODO Remove Testdata, atm always int */
    public Type type = new Type(false, 0, "int");;

    public String value; //Ok for int, double, char, boolean, String

    public Object jjtAccept(NewAwkParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    @Override
    public String toString() {
        return "ExprStmnt{" +
                "type=" + type +
                ", value='" + value + '\'' +
                '}';
    }
}
