/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for IntegerLiteral Token subclass
  * by the ASTToken.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

import static de.compilerbau.NewAwkCompiler.javacc21.NewAwkConstants.TokenType.*;
@SuppressWarnings("unused")
public class IntegerLiteral extends Token {

    public int intValue = 0;


    public IntegerLiteral(){

    }

    public IntegerLiteral(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

    public IntegerLiteral(TokenType type, String image, FileLineMap fileLineMap) {
        super(type, image, fileLineMap);
    }


    public int getIntValue() {
        return intValue;
    }

    public void setIntValue(int intValue) {
        this.intValue = intValue;
    }
}
