/* Generated by: JavaCC 21 Parser Generator. InvalidToken.java */
package de.compilerbau.NewAwkCompiler.javacc21;

/**
 * Token subclass to represent lexically invalid input
 */
public class InvalidToken extends Token {
    public InvalidToken(String image, FileLineMap inputSource) {
        super(TokenType.INVALID, image, inputSource);
    }

    /*    
    public InvalidToken() {
       super(TokenType.INVALID, null, "input");
    }
*/
    public String getNormalizedText() {
        return"Lexically Invalid Input:"+getImage();
    }

    public boolean isDirty() {
        return true;
    }

}
