/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for KlammerAffeAusdruck AST Node type
  * by the ASTNode.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

import de.compilerbau.NewAwkCompiler.Visitors.RegexAction;

@SuppressWarnings("unused")
public class KlammerAffeAusdruck extends BaseNode {

    public boolean regexConditionalNot;
    public Type regexType = null;
    public String regexString = null;
    public Type actionType = null;
    public String actionValue = null;

    public Object jjtAccept(NewAwkParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    @Override
    public String toString() {
        return "KlammerAffeAusdruck{" +
                "regexConditionalNot=" + regexConditionalNot +
                ", regexType=" + regexType +
                ", regexString='" + regexString + '\'' +
                ", actionType=" + actionType +
                ", actionValue='" + actionValue + '\'' +
                '}';
    }
}
