/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for KlammerAffeStringRegex AST Node type
  * by the ASTNode.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

import static de.compilerbau.NewAwkCompiler.javacc21.NewAwkConstants.TokenType.*;
@SuppressWarnings("unused")
public class KlammerAffeStringRegex extends BaseNode {
}
