/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for LogicalOrExpr AST Node type
  * by the ASTNode.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

import static de.compilerbau.NewAwkCompiler.javacc21.NewAwkConstants.TokenType.*;
@SuppressWarnings("unused")
public class LogicalOrExpr extends BaseNode {

    public Type type = null;
    public String value = null;

    public Object jjtAccept(NewAwkParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    @Override
    public String toString() {
        return "LogicalOrExpr{" +
                "type=" + type +
                ", value='" + value + '\'' +
                '}';
    }
}
