/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for Method AST Node type
  * by the ASTNode.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

@SuppressWarnings("unused")
public class Method extends BaseNode {
}
