/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for MethodDecl AST Node type
  * by the ASTNode.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

import java.util.List;
@SuppressWarnings("unused")
public class MethodDecl extends BaseNode {

    // Method-return Type
    public Type type;
    //Method-ID/Name
    public String id;
    //Parameters in Parameterlist
    public List<ParameterEntry> parameterList;
    //Statements in the Methodblock
    public List<Stmnt> statements;




    public Object jjtAccept(NewAwkParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
