/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for MODULO Token subclass
  * by the ASTToken.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

import static de.compilerbau.NewAwkCompiler.javacc21.NewAwkConstants.TokenType.*;
@SuppressWarnings("unused")
public class MODULO extends Token {
    public MODULO(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

    public MODULO(TokenType type, String image, FileLineMap fileLineMap) {
        super(type, image, fileLineMap);
    }

}
