/* Generated by: JavaCC 21 Parser Generator. Do not edit. NewAwkParserVisitor.java */
package de.compilerbau.NewAwkCompiler.javacc21;

public interface NewAwkParserVisitor {
    Object visit(BaseNode node, Object data);
    Object visit(Program node, Object data); 
    Object visit(FieldOrMethods node, Object data); 
    Object visit(FieldDeclarationAndAssignment node, Object data); 
    Object visit(Assignment node, Object data); 
    Object visit(ArrayAssignment node, Object data); 
    Object visit(Method node, Object data); 
    Object visit(MethodSignature node, Object data); 
    Object visit(ParameterList node, Object data); 
    Object visit(MethodBody node, Object data); 
    Object visit(ReturnStatement node, Object data); 
    Object visit(Comparision node, Object data); 
    Object visit(Token node, Object data); 
}
