/* Generated by: JavaCC 21 Parser Generator. Do not edit. NewAwkConstants.java */
package de.compilerbau.NewAwkCompiler.javacc21;

/**
 * Token literal values and constants.
 */
public interface NewAwkConstants {
    public enum TokenType {
        EOF, WHITESPACE, TAB, NEW_LINE, CARRIAGE_RETURN, PLUS, MINUS, MULTIPLICATION, DIVISION, MODULO, Zuweisung, EQUAL, NOT_EQUAL, G_OR_EQUAL, S_OR_EQUAL, GREATER, SMALLER, Colon, ConditionalAnd, ConditionalOr, ConditionalNot, Exponentiation, RETURN, KlammerAuf, KlammerZu, BlockAuf, BlockZu, LBRACKET, RBRACKET, SEMICOLON, COMMA, DOT, LETTER, DIGIT, EXPO, DataType, ArrayType, Apostrophe, BooleanConditionalAnd, BooleanConditionalOr, BooleanConditionalNot, CharLiteral, VOID, NullLiteral, BooleanValue, TRUE, FALSE, IntegerLiteral, DoubleLiteral, Bezeichner, StringLiteral, STRING_CONTENT, INVALID
    }
    /**
   * Lexical States
   */
    public enum LexicalState {
        DEFAULT, 
    }
    String[] tokenImage= {"<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"+\"", "\"-\"", "\"*\"", "\"/\"", "\"%\"", "\"=\"", "\"==\"", "\"!=\"", "\">=\"", "\"<=\"", "\">\"", "\"<\"", "\":\"", "\"&&\"", "\"||\"", "\"!\"", "\"^\"", "\"return\"", "\"(\"", "\")\"", "\"{\"", "\"}\"", "\"[\"", "\"]\"", "\";\"", "\",\"", "\".\"", "<LETTER>", "<DIGIT>", "<EXPO>", "<DataType>", "<ArrayType>", "\"\\\'\"", "<BooleanConditionalAnd>", "<BooleanConditionalOr>", "<BooleanConditionalNot>", "<CharLiteral>", "\"void\"", "\"null\"", "<BooleanValue>", "\"true\"", "\"false\"", "<IntegerLiteral>", "<DoubleLiteral>", "<Bezeichner>", "<StringLiteral>", "<STRING_CONTENT>", };
}
