/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for ParameterList AST Node type
  * by the ASTNode.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

@SuppressWarnings("unused")
public class Parameter {

    public Type type;
    public ID id;

    public Parameter(Type type, ID id) {
        this.type = type;
        this.id = id;
    }

    @Override
    public String toString() {
        return "Parameter{" +
                "type=" + type +
                ", id=" + id +
                '}';
    }
}
