/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for ParameterList AST Node type
  * by the ASTNode.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

import java.util.List;
import java.util.Map;

import static de.compilerbau.NewAwkCompiler.javacc21.NewAwkConstants.TokenType.*;
@SuppressWarnings("unused")
public class ParameterList extends BaseNode {

    public List<ParameterEntry> parameterList;

    public void addParameterEntry(){

    }

    public Object jjtAccept(NewAwkParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
