/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for ParameterList AST Node type
  * by the ASTNode.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

import java.util.List;

@SuppressWarnings("unused")
public class ParameterEntry {

    public Type type;
    public ID id;

}
