/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for RBRACKET Token subclass
  * by the ASTToken.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

@SuppressWarnings("unused")
public class RBRACKET extends Token {
    public RBRACKET(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

    public RBRACKET(TokenType type, String image, FileLineMap fileLineMap) {
        super(type, image, fileLineMap);
    }

}
