/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for VariableDecl AST Node type
  * by the ASTNode.java.ftl template
  */
package de.compilerbau.NewAwkCompiler.javacc21;

@SuppressWarnings("unused")
public class VariableDecl extends BaseNode {

    public Type type = null;
    public ID id = null;
    /**
     * Value is not assigned at the init of a new {@link VariableDecl}-Object
     * its assigned when a {@link Assignement} is done,
     * or if {@link VariableDeclAndAssignement} is called
     */
    public String value = null;

    public Object jjtAccept(NewAwkParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public VariableDecl() {
    }

    public VariableDecl(Type type, ID id) {
        this.type = type;
        this.id = id;
        this.value = null;
    }

    public VariableDecl(Type type, ID id, String value) {
        this.type = type;
        this.id = id;
        this.value = value;
    }

    @Override
    public String toString() {
        return "VariableDecl{" +
                "type=" + type +
                ", id=" + id +
                ", value='" + value + '\'' +
                '}';
    }
}
